version: '3.8'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3001:3001'
        environment:
            # Aqui, certifique-se de que esta variável usa o nome do container Mongo do outro projeto
            MONGODB_URI: mongodb://shared-postgres:27017/shared_db
            MERCADO_PAGO_API: ${MERCADO_PAGO_API}
            MERCADO_PAGO_CLIENT_SECRET: ${MERCADO_PAGO_CLIENT_SECRET}
            MERCADO_PAGO_CLIENT_ID: ${MERCADO_PAGO_CLIENT_ID}
            MERCADO_PAGO_QR_CODE_API: ${MERCADO_PAGO_QR_CODE_API}
            MERCADO_PAGO_WEBHOOK: ${MERCADO_PAGO_WEBHOOK}
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: food2025
            MYSQL_DATABASE: fast_food
        depends_on:
            - mysql
        volumes:
            - ./src:/app/src
        networks:
            - shared-mysql
            - shared-net

    mysql:
        image: mysql:latest
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: food2025
            MYSQL_USER: food
            MYSQL_DATABASE: fast_food
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - shared-mysql


volumes:
    mysql_data:

networks:
    shared-net:
        external: true
    shared-mysql:
     
