services:
    order-service:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3001:3001'
        environment:
            # Aqui, certifique-se de que esta variável usa o nome do container Mongo do outro projeto
            MONGODB_URI: mongodb://mongo:27017/shared_db
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: food2025
            MYSQL_DATABASE: fast_food
        depends_on:
            - mysql
        volumes:
            - ./src:/app/src
        networks:
            - shared-mysql
            - shared-net
            - fast-food-network

    mongo:
        image: mongo:latest
        command:
            - '--logpath'
            - '/var/log/mongodb/mongod.log'
        volumes:
            - mongo_data:/data/db
        networks:
            - fast-food-network
            - shared-net

    mysql:
        image: mysql:latest
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: food2025
            MYSQL_USER: food
            MYSQL_DATABASE: fast_food
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - shared-mysql
            - fast-food-network

volumes:
    mysql_data:
    mongo_data:

networks:
    shared-net:
        external: true
    shared-mysql:
    fast-food-network:
