apiVersion: v1
kind: Service
metadata:
    name: fast-food-service
spec:
    selector:
        app: fast-food
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
    type: LoadBalancer
