apiVersion: v1
kind: Service
metadata:
    name: order-service
spec:
    selector:
        app: fast-food-order
    ports:
        - protocol: TCP
          port: 3001
          targetPort: 3001
          nodePort: 32001
    type: NodePort
