export const ORDER_STATUS = {
    AWAITING_PAYMENT: 'AWAITING_PAYMENT',
    RECEIVED: 'RECEIVED',
    IN_PREPARATION: 'IN_PREPARATION',
    READY: 'READY',
    COMPLETED: 'COMPLETED',
}

export const ORDER_STATUS_LIST = [
    ORDER_STATUS.RECEIVED,
    ORDER_STATUS.IN_PREPARATION,
    ORDER_STATUS.READY,
    ORDER_STATUS.COMPLETED,
]
